TRAIN:
  ENABLE: True
  DATASET: aria_av_gaze_forecast
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True  # reset epoch and optimizer when finetuning
DATA:
  PATH_PREFIX: '/data/blai38/Datasets/Aria/clips'
#  DECODING_BACKEND: torchvision  # comment this line to use pyav as decoder
  NUM_FRAMES: 8
  SAMPLING_RATE: 4  # sample 1 frame in every 5 frames
  TRAIN_JITTER_SCALES: [256, 320]
#  TRAIN_JITTER_SCALES: [256, 288]  # can result in better result
  TRAIN_CROP_SIZE: 256  # from 224
  TEST_CROP_SIZE: 256  # from 224
  INPUT_CHANNEL_NUM: [3]
#  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
#  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  TARGET_FPS: 20
  USE_OFFSET_SAMPLING: False  # modified from True
  GAUSSIAN_KERNEL: 19
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 16
  NUM_HEADS: 1  # base number of head for transformer
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  AUDIO_BRANCH_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DROPOUT_RATE: 0.0
#  GLOBAL_EMBED_ON: True  # For rebuttal only
#AUG:
#  NUM_SAMPLE: 2
#  ENABLE: True
#  COLOR_JITTER: 0.4
#  AA_TYPE: rand-m7-n4-mstd0.5-inc1
#  INTERPOLATION: bicubic
#  RE_PROB: 0.25
#  RE_MODE: pixel
#  RE_COUNT: 1
#  RE_SPLIT: False
#MIXUP:
#  ENABLE: True
#  ALPHA: 0.8
#  CUTMIX_ALPHA: 1.0
#  PROB: 1.0
#  SWITCH_PROB: 0.5
#  LABEL_SMOOTH_VALUE: 0.1
BN:
  USE_PRECISE_STATS: False  # default False for MViT
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6  # modified from 1e-6
  WARMUP_EPOCHS: 0.0  # modified from 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 15  # modified from 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 400
  ARCH: mvit
  MODEL_NAME: CSTS
  LOSS_FUNC: kldiv
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: aria_av_gaze_forecast
  BATCH_SIZE: 96
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
  FULL_FRAME_TEST: False
DATA_LOADER:
  NUM_WORKERS: 8  # set as 0 if you want to add breaking point in _getitem_()
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True

LOG_MODEL_INFO: False
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 42
OUTPUT_DIR: .
